apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-update-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-authorization-cluster-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "delete"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-aws-authorization-binding
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: aws-authorization-cluster-role
subjects:
- kind: ServiceAccount
  name: ecr-update-service-account
  namespace: infrastructure
